name: PTK
description: Puzzak's ToolKit

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.3+3

environment:
  sdk: '>=2.19.3 <3.0.0'


dependencies:
  http: ^1.1.2
  xml: ^6.5.0
  intl: ^0.17.0
  url_launcher: ^6.1.10
  shared_preferences: ^2.0.12
  material_design_icons_flutter: 7.0.7296
  charts_flutter_new: ^0.12.0
  dynamic_color: ^1.6.9

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/data/authors.json

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa.ttf